jobs:
  build_linux:
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    name: Build with Java ${{ matrix.java }} in Ubuntu
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        architecture: x64
        cache: maven
        distribution: zulu
        java-package: jdk
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B -ff -ntp clean install -Dgpg.skip=true
    - continue-on-error: true
      if: github.ref == 'refs/heads/main' && matrix.java == '11'
      name: Publish Code Coverage
      uses: codecov/codecov-action@v4
      with:
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      matrix:
        java:
        - '11'
        - '17'
  build_macos:
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    name: Build with Java ${{ matrix.java }} in MacOS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        architecture: x64
        cache: maven
        distribution: zulu
        java-package: jdk
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B -ff -ntp clean install -Dgpg.skip=true
    strategy:
      matrix:
        java:
        - '11'
        - '17'
  build_windows:
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    name: Build with Java ${{ matrix.java }} in Windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        architecture: x64
        cache: maven
        distribution: zulu
        java-package: jdk
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B -ff -ntp clean install --% -Dgpg.skip=true
    strategy:
      matrix:
        java:
        - '11'
        - '17'
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
